name: End-to-end tests 游빍     # Nome do pipeline
on: [push]                    # O pipeline ser치 disparado sempre que tiver um "Git Push"
jobs:                         # Indica o que ser치 feito...  
  cypress-run:                # Ir치 rodar o cypress run
    runs-on: ubuntu-20.04     # Com a imagem do Ubuntu
    steps:                    # Vai rodar os seguintes passos abaixo
      - name: Checkout
        uses: actions/checkout@v2  # O checkout ir치 baixar o c칩digo do projeto no workspace do github actions
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4  # Indica que vai rodar o cypress run com a imagem do github actions